### ISSUE TITLE
Error java.time.format.DateTimeParseException: Text '4-02-10' could not be parsed at index 0

### ISSUE THREAD

**Issue by TomVanAken** [OpenNTF/org.openntf.xsp.jakartaee#153]
I'm testing using v2.3.0 demo database and the openntf download v2.3.0

I get this error when retrieving calling <nsf-path>/xsp/app/nosql/list

The same error was given on nosql.xsp page.
The error is always the same, regardless of any date entered.

**Comment by TomVanAken** [comment]
Probable cause: While creating a new person (xsp/app/nosql/create), I mistyped the birthdate. It was stored with year 4 (not 2004).
After deleting this record, it works fine.

**Comment by jesse-gallagher** [comment]
That makes sense. While it may just be a data issue to avoid, did it give a full stack trace? I could use that to check if it's something that could realistically be handled better in the driver.
