### ISSUE TITLE
Make it possible to override/control 'url' in openapi

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#175]
For instance if you want to expose a different hostname and/or a different JAX-RS root. I have an internet site rule that points /api to /xsp/app and would like openapi to use /api in the generated 'url'.

**Comment by jesse-gallagher** [comment]
This should be doable by specifying the property `mp.openapi.servers` in your Xsp Properties file (or anything else registered in MP Config). With the commits just added a few minutes ago, there's a test verifying that this should work.
