### ISSUE TITLE
JAX-RS timeout issue

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#188]
After a while (for instance when testing in the morning) the JAX-RS API fails for some of my custom code with HTTP 500 and the output is the error form that I have configured in domcfg under "Error & Response Form Mappings". I see no other logged errors (I have checked log.nsf, console.log, XPages log file, error-0.log, trace-0.log).

The API still works for other (more simple) custom code.

If I restart HTTP, the custom code works again (until the next morning).

Let me know if there is any logging that I can introduce to help locate the problem.

**Comment by jesse-gallagher** [comment]
Hmm, interesting. I assume this is related to the XPages application timeout - I've tweaked a number of things to try to respect that better over time, but it's difficult to make sure everything is lined up.

Is there anything obviously distinct between the services that do and don't work? Like, say, use of lotus.domino objects, use of scoped CDI beans, etc.

**Comment by perlausten** [comment]
I don't see any obvious differences that should explain it.

I did not test it this morning but I have used the "XPages part" of the application today and the API works. So it indicates that it's related to XPages application timeout, as you mention.

**Comment by perlausten** [comment]
I have not been able to reproduce the error so I will close the issue.
