### ISSUE TITLE
Deserialization of Map key with backslash fails

### ISSUE THREAD

**Issue by esvechnikov** [OpenNTF/org.openntf.xsp.jakartaee#338]
Describe the bug
When deserializing a Map with a key containing a \ an exception is thrown.

Discussion of the problem
https://github.com/eclipse-ee4j/yasson/issues/540?ysclid=l95hvotxx8624587068

```
@Test
	public void testExampleBean() {
		Jsonb jsonb = JsonbBuilder.create();
		
		ExampleBean bean = new ExampleBean();
		bean.setFoo("hello\\hello");
		bean.setBar("world");
		String json = JSONBindUtil.toJson(bean, jsonb);
		assertEquals("Serialized bean should match expected", "{\"bar\":\"world\",\"foo\":\"hello\\hello\"}", json);
		
		ExampleBean bean2 = JSONBindUtil.fromJson(json, jsonb, ExampleBean.class);
		assertEquals("Beans should be equivalent", bean, bean2);
	}
```

**Comment by jesse-gallagher** [comment]
Hmm, this may be tricky. I expect that the next major version of the spec they mention there requires Java 11 and this won’t run on Domino. I’ll have to ponder options here.

**Comment by jesse-gallagher** [comment]
I think I was able to fix the issue by switching the JSON-P/B implementation to Apache Johnzon instead of the GlassFish-derived implementations. It should be fixed for 2.9.0.

**Comment by esvechnikov** [comment]
I made a mistake in my tests with json and backslash. Probably should go back to using yasson  as it implements JSON-P/B 2.

**Comment by jesse-gallagher** [comment]
I reproduced the trouble with the `Map` example in the linked issue, so it was definitely worth fixing. Though Johnzon is written to the older spec, I run the dependencies through Eclipse Transformer to make them compatible with the JEE 9 target this has, so it's a clean replacement.
