### ISSUE TITLE
java.lang.IllegalStateException using BufferedReader 

### ISSUE THREAD

**Issue by DanieleVistalli** [OpenNTF/org.openntf.xsp.jakartaee#364]
We tried implementing a Slack bot using slack's official SDK (Bolt).

When Invoking the servlet we are experiencing the exception detailed below:

> **java.lang.IllegalStateException: Cannot use BufferedReader while ServletInputStream is in use**

I looked up the OldHttpServletRequestWrapper class and found that:

**getInputStream** is decorated by the adapter: https://github.com/OpenNTF/org.openntf.xsp.jakartaee/blob/0e9f200d1c52a3669803b5393c439663cb9f9cba/eclipse/bundles/org.openntf.xsp.jakartaee.commons/src/org/openntf/xsp/jakartaee/servlet/OldHttpServletRequestWrapper.java#L102

**getReader** is plain calling the delegate: https://github.com/OpenNTF/org.openntf.xsp.jakartaee/blob/0e9f200d1c52a3669803b5393c439663cb9f9cba/eclipse/bundles/org.openntf.xsp.jakartaee.commons/src/org/openntf/xsp/jakartaee/servlet/OldHttpServletRequestWrapper.java#L157

I'm not sure if the exception can be managed by also decorating the getReader() call or if this is a limit that cannot be worked around.

Below the entire stack trace.

> java.lang.IllegalStateException: Cannot use BufferedReader while ServletInputStream is in use
    com.ibm.domino.xsp.bridge.http.servlet.XspCmdHttpServletRequest.getReader(XspCmdHttpServletRequest.java:1412)
    com.ibm.designer.runtime.domino.adapter.servlet.LCDAdapterHttpServletRequest.getReader(LCDAdapterHttpServletRequest.java:324)
    org.openntf.xsp.jakartaee.servlet.OldHttpServletRequestWrapper.getReader(OldHttpServletRequestWrapper.java:158)
    com.slack.api.bolt.jakarta_servlet.ServletAdapterOps.doReadRequestBodyAsString(ServletAdapterOps.java:19)
    com.slack.api.bolt.jakarta_servlet.SlackAppServletAdapter.doReadRequestBodyAsString(SlackAppServletAdapter.java:44)
    com.slack.api.bolt.jakarta_servlet.SlackAppServletAdapter.buildSlackRequest(SlackAppServletAdapter.java:31)
    com.slack.api.bolt.jakarta_servlet.SlackAppServlet.doPost(SlackAppServlet.java:33)
    jakarta.servlet.http.HttpServlet.service(HttpServlet.java:520)
    jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
    org.openntf.xsp.jakarta.servlet.nsf.XspServletWrapper.doService(XspServletWrapper.java:64)
    org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.service(AbstractXspLifecycleServlet.java:129)
    jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
    org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:112)
    com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)
    com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)
    com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)
    com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)
    com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
    com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
    com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
    com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
    com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)
    com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)
    com.mindoo.domino.jna.gc.NotesGC$1.run(NotesGC.java:537)
    java.security.AccessController.doPrivileged(AccessController.java:682)
    com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:532)
    com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)
    com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
    com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
    com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)

**Comment by jesse-gallagher** [comment]
Hrm, interesting. In theory, having that wrapper there should be inert if you're not calling that method. I don't have a wrapper for the `Reader` because there's no specialized Servlet version of the type returned, so we _shouldn't_ need one.

I wonder if something in here is calling `getInputStream()` beforehand... it _shouldn't_, but that would certainly cause that trouble. I'll see if I can reproduce the trouble.

**Comment by jesse-gallagher** [comment]
I see this happens with an installation that only has XPages JEE installed and with a Servlet that just echoes the incoming payload back, so the trouble must be in this project.

**Comment by DanieleVistalli** [comment]
Possibly the servletutil doing the transformation is triggering some statechange on the inputstream. (Just guessing).

Good to know you've been able to reproduce.

**Comment by jesse-gallagher** [comment]
Moreover, it's definitely specific to Jakarta Servlets in NSFs: a legacy Servlet in an NSF (whether or not that NSF also has Jakarta libraries enabled) works fine.

**Comment by jesse-gallagher** [comment]
The trouble comes in somewhere with the use of the Faces-lifecycle wrapper Servlet. If I skip that part, the Servlet executes without issue.

This is a sticky problem, though. I use that Faces-lifecycle wrapper to allow the Servlet to participate in the full app lifecycle, which means that it gets `sessionAsSigner` and, importantly, kicks off all the app-init listeners for CDI and the like.

I'll try to see if I can track down the part of the XSP stack that calls this and work around it. I assume that it's something that checks for a viewId in the POST data to re-hydrate a saved view. If so, I could work around it by having a specialized request wrapper that returns an empty stream.

Failing that, I may add an annotation that one could put on their Servlet class to have it opt out of the Faces context. That should work for cases like this, where presumably you're just wrapping the stock Slack Servlet outright.

**Comment by DanieleVistalli** [comment]
Wow, thank you for the quick analysis. 

In our use case the slack servlet is anonymous but then needs to access sessionAsSigner to interact with db data.

Opting out of lifecycle (if I understand your comment) would strip this Injection possibility away.

Thank you for investigating.
