### ISSUE TITLE
Boolean conversion

### ISSUE THREAD

**Issue by monstermichl** [OpenNTF/org.openntf.xsp.jakartaee#494]
Hey Jesse, for a while I have been using strings as boolean values now because I encountered that boolean values are stored as "Y" or "N" when saved. However, they are not converted back correctly, hence the usage of strings. E.g.,

```java
@Column("active")
private String _active;
```

instead of 

```java
@Column("active")
private boolean _active;
```

Is it on purpose that booleans are not converted? I only found [this](https://github.com/OpenNTF/org.openntf.xsp.jakartaee/issues/96) issue but I'm not sure if it's related to that. Also, I found [this](https://github.com/OpenNTF/org.openntf.xsp.jakartaee/blob/a0bcf7c82edfc1049e565e7525ed53c6e76f92d2/eclipse/bundles/org.openntf.xsp.nosql.driver.lsxbe/src/org/openntf/xsp/nosql/communication/driver/lsxbe/util/DominoNoSQLUtil.java#L86C8-L86C8) in the source code but couldn't find code that converts it the other way.

BR
Michel

**Comment by jesse-gallagher** [comment]
I set up a basic test that tries to round-trip a boolean value and it looks like I see the same thing. I'll investigate.

**Comment by jesse-gallagher** [comment]
Should be improved in 2.15.0. In addition to fixing the broken default behavior, I added a `@BooleanStorage` annotation to control the true and false values, allowing either strings or doubles.

**Comment by monstermichl** [comment]
Awesome, thanks :)
