### ISSUE TITLE
Repository findFirst

### ISSUE THREAD

**Issue by monstermichl** [OpenNTF/org.openntf.xsp.jakartaee#512]
Hey Jesse,

I'm trying to get our application faster and found that one of my bottlenecks is to get the first element of a large database. I tried to define a method in my repository like *Optional\<T\> findFirst()* but it throws an exception. I also tried *Stream\<T\> findAll(Pagination pagination)* which works but is really, really slow. So my current approach is *repository.findAll().findFirst()* which is about as slow as *findAll* with pagination. For our application it takes about 2 - 3 seconds. Do you have any idea, if there could be a faster way?

Thanks and BR
Michel

**Comment by jesse-gallagher** [comment]
For now, I think your best bet will be to have a view and use `@ViewEntries` or `@ViewDocuments` to annotate a repository method.

While I try to keep things efficient in the normal case, I'm eventually bound by [the characteristics of a DQL query](https://github.com/OpenNTF/org.openntf.xsp.jakartaee/blob/develop/eclipse/bundles/org.openntf.xsp.nosql.driver.lsxbe/src/org/openntf/xsp/nosql/communication/driver/lsxbe/impl/DefaultDominoDocumentCollectionManager.java#L289), and I imagine that the query execution takes a while.

You may be able to improve the normal case by making sure you have a view that DQL can use as an index and using [explain](https://help.hcltechsw.com/dom_designer/12.0.2/basic/dql_explain.html) in an agent to make sure it's being used. However, the `@ViewEntries`/`@ViewDocuments` route gets to [use ViewNavigators](https://github.com/OpenNTF/org.openntf.xsp.jakartaee/blob/develop/eclipse/bundles/org.openntf.xsp.nosql.driver.lsxbe/src/org/openntf/xsp/nosql/communication/driver/lsxbe/impl/DefaultDominoDocumentCollectionManager.java#L311) to be pretty inherently efficient even with the limitations of the API.

**Comment by monstermichl** [comment]
Thanks for the hints. I thought about it and I actually don't really need a document from the database, I just need an instance of the Entity. However, my DominoDocumentRepositoryBase takes a generic type and therefore I cannot just instantiate this type. How do you instantiate the type that is passed to the repository? To know that might help me.

```java
public interface DominoDocumentRepositoryBase<T extends DominoDocumentEntityBase> extends DominoRepository<T, String> {
	public Stream<T> findAll();
	public Stream<T> findAll(Pagination pagination);
}
```

**Comment by jesse-gallagher** [comment]
If you just want any old instance without caring if it comes from the DB, you can treat it like a normal Java object and do `SomeEntity foo = new SomeEntity()`. Entities in JNoSQL don't actually retain any connection to the backing DB, so you can freely create them.

**Comment by monstermichl** [comment]
Yes, I know. However, I don't know what's the type because the class that handles my logic is a generic class and therefore I cannot just do new T() because Java doesn't know the actual type.

```java
public abstract class DominoDocumentServiceBase<T extends DominoDocumentEntityBase, U extends DominoDocumentRepositoryBase<T>> {
   ...
}
```

**Comment by monstermichl** [comment]
Since I have an abstract class around the repository anyway, I solved it by forcing the derivative classes to create a new object of the respective class. If you think there's a better way, please let me know.

**Comment by jesse-gallagher** [comment]
Hmm, yeah, I see how this is a weird one. You could likely do it with a utility method that finds the eventual implementation of `Repository` for the actual class and then gleans the type parameter using reflection - that's presumably what the JNoSQL code does internally for this, though I'm not sure where at the moment that is. You could do a less-scalable but also less-ugly version by having a utility method that does an `instanceof` check for your known repositories - kind of sucky in that you'd have to maintain it manually, though.

**Comment by monstermichl** [comment]
No, honestly in this case I really prefer the abstract class method because the derivative has to implement some methods anyway already :)
