### ISSUE TITLE
HTML special characters

### ISSUE THREAD

**Issue by monstermichl** [OpenNTF/org.openntf.xsp.jakartaee#535]
Hey Jesse,

just a question. Which library or function do you use to convert HTML escaped strings (e.g. &#xf6;) back to text? I thought there might be something in Jakarta.

BR
Michel

**Comment by jesse-gallagher** [comment]
Hmm, not that I know of - I've often gone the other direction, but not _decoding_ HTML entities. It's possible that there may be something tucked away in, say, the JSF or JSP bundles that are exposed to the NSF. Failing that, I'd try a library like Jsoup that understands HTML entities (which just a normal XML parser wouldn't).

**Comment by monstermichl** [comment]
Hey Jesse, thanks for your response. Yes, I solved it with Jsoup. BR
