### ISSUE TITLE
sessionAsSigner is generally null on first XPage request

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#60]
This is likely a problem with this library, though I suppose it's possible it's broken in 12.0.1. Either way, the first request to an XPage resolving sessionAsSigner will find `null`, but subsequent ones will retrieve it properly.

**Comment by jesse-gallagher** [comment]
This is indeed specific to the use of this library: another DB on the server without using EL or CDI doesn't exhibit this behavior.

It's also not specific to the EL interpreter as such: using the `xspel:` version also is blank on first load after an app refresh. This makes sense, at least, as the ELResolver finds the value from the delegate `null` on first load.

**Comment by jesse-gallagher** [comment]
It also isn't caused by the JSP, JAX-RS, or MVC libraries: the same behavior happens when those are deleted from the server.

**Comment by jesse-gallagher** [comment]
It appears to be related to having the CDI feature enabled: with it disabled in any configuration, it succeeds each time; with it enabled, it always fails the first time.

**Comment by jesse-gallagher** [comment]
It's also not inherent to resolving from the delegate resolver: a managed bean defined in faces-config (and thus not picked up by CDI) works consistently.

**Comment by guedeWebGate** [comment]
Jesse I see this behavior with different signers in the same database. I recommend to check this first

**Comment by jesse-gallagher** [comment]
That was something I checked early, since I thought it could be an easy culprit. Unfortunately, I'm the only signer, and re-signing the DB doesn't change it. It does seem to be dependent specifically on the use of the CDI library, so I'll have to figure out where it's going awry.

**Comment by jesse-gallagher** [comment]
It seems that something in calling `ContainerUtil.getContainer(application)` in the ApplicationListener's applicationCreated event did it. Perhaps doing the classpath scanning (by the BeanArchiveHandler) that early in initialization caused trouble.

Fortunately, that call was only there to work around something that showed up in early development and doesn't seem to be actually required now. I'll keep an eye out for trouble, but it seems that removing that call fixes it.
