### ISSUE TITLE
Add support for per-resource role-based security

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#66]
The JAX-RS API (/xsp/app) is publicly available for anonymous even though anonymous is set to No Access in the ACL. It does not seem to matter if anonymous has Read Public Documents set or not.

It should be possible to restrict access to authenticated users.

**Comment by jesse-gallagher** [comment]
Makes sense, and this would be a good opportunity to implement `@RolesAllowed`, too.

**Comment by perlausten** [comment]
@jesse-gallagher do you see the same authentication issue in the apps that you have ported to use your project and JAX-RS for API?

**Comment by jesse-gallagher** [comment]
In my uses, I actually just use the RESTEasy version provided by this project as the engine for OSGi-provided services and don't actually have any in-NSF ones. Which, admittedly, limits my testing regime.
