### ISSUE TITLE
Domino elements injected into CDI beans are retained across requests

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#83]
This seems to be a generalized version of https://github.com/OpenNTF/org.openntf.xsp.jakartaee/issues/61 , but occurs even when a bean is `@RequestScoped` or `@Dependent`.

**Comment by DanieleVistalli** [comment]
What if we make those CDI beans @RequestScoped ? I think your CDI bean provider can be configured so that those injections are request scoped. Is this an option you are valuating ?

**Comment by jesse-gallagher** [comment]
I originally figured that was the problem, but doing that didn't fix it - it seems that the proxies are actually retained and not replaced with new values even when marked as `@RequestScoped`, and I'm not sure why. I had some success in MVC with marking the bean being injected into as `@Dependent`, but that's not consistent: https://github.com/OpenNTF/org.openntf.xsp.jakartaee/issues/61

**Comment by DanieleVistalli** [comment]
Got, it
